name: auto build

on:
  push:
    branches:
      - ls_icons

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: aeiouaoeiuv/ubuntu:ls_icons
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        run: |
          git config --global --add safe.directory $PWD
          git submodule update --init --recursive
          ./bootstrap
          export CC=clang CXX=clang++
          FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=${PWD}/install
          make
          make install
          strip install/bin/ls
      -
        name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ls
          path: install/bin/ls

